### ISSUE TITLE
Suchfilter

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium-Embed#11]
Ein entsprechender Filter soll ebenfalls -sowohl eigenständig als Shortcode einbaubar, aber auch optional ergänzend zusammen mit der Wortsuche https://github.com/RRZE-Webteam/FAU-Studium/issues/1 umgesetzt werden.

Suchfilter sollen folgende Felder betreffen:

- Studienart
- Fächergruppen
- Sprachen

**Comment by xwolfde** [comment]
Erfüllt
