### ISSUE TITLE
Suchfunktion nutzerfreundlicher (und trotzdem barrierefrei) gestalten

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium-Embed#16]
<img width="743" alt="image" src="https://github.com/RRZE-Webteam/FAU-Studium-Embed/assets/9526974/44944154-0eb5-4767-83ef-55fe1ca088ed">

Nach der Auswahl bei einem Filter muss der Nutzer noch einmal auf den "Suchen"-Button oberhalb der Auswahlfelder klicken. Schöner wäre es, wenn der Filter gleich nach dem Anhaken die Studiengangsliste neu sortiert. Es ist leider nicht intuitiv, nach der Auswahl noch einmal weiter oben auf "suchen" zu klicken.

**Comment by xwolfde** [comment]
Gilt natürlich nur für Desktop und für Mausbenutzer.

**Comment by wrcg** [comment]
wurde umgesetzt
